switchinfo/urls.py
from django.urls import path

from . import views

app_name = 'switchinfo'
urlpatterns = [
    path('switch/<str:switch_name>/load_interfaces', views.load_interfaces,
         name='switch_load_interfaces'),
    path('switch/<str:switch_name>/load_mac', views.load_mac,
         name='switch_load_mac'),
    path('switch', views.switches),
    path('switch/ip/<str:ip>', views.show_switch, name='switch'),
    path('switch/<str:name>.json', views.switch_json, name='switch_json'),
    path('switch/<str:name>', views.show_switch, name='switch'),
    path('switch/<str:switch_name>/vlans', views.vlans_on_switch, name='switch_vlans'),
    path('switch/<str:switch_name>/vlans.txt', views.vlans_on_switch, name='switch_vlans_cli'),
    path('switch/<str:switch_name>/vlans.json', views.vlans_on_switch, name='switch_vlans_json'),
    path('', views.switches, name='switches_index'),
    path('switches', views.switches, name='switches'),
    path('switches.json', views.switches_json, name='switches_json'),
    path('switches/group', views.switches_group, name='groups'),
    path('vlan/<int:vlan>', views.vlan_ports, name='vlan'),
    path('vlans', views.vlans, name='vlans'),
    path('models', views.models, name='models'),
    path('model/<str:model>', views.switch_model, name='switch_model'),
    path('series/<str:series>', views.switch_model, name='switch_series'),
    path('search', views.search_form, name='search'),
    path('mac/<str:mac>', views.mac_search, name='mac'),
    path('mac.json/<str:mac>', views.mac_search_json, name='mac_json'),
    path('ip/<str:ip>', views.ip_search, name='ip'),
    path('hosts', views.hosts, name='hosts'),
]

switchinfo/models.py
import os.path
import re

from django.apps import apps
from django.conf import settings
from django.db import models

if hasattr(settings, 'TRUNK_FORCE_MAC'):
    trunk_force_mac = settings.TRUNK_FORCE_MAC
else:
    trunk_force_mac = ['Mitel IP Phone']


class Switch(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True)
    location = models.CharField(max_length=100, blank=True, null=True)
    ip = models.GenericIPAddressField()
    has_poe = models.BooleanField(default=False)
    type = models.CharField(max_length=50, blank=True, null=True)
    community = models.CharField(max_length=50, default='Public')
    model = models.CharField(max_length=100, blank=True, null=True)
    series = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField(max_length=500, blank=True, null=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'switches'

    def __str__(self):
        return '%s (%s)' % (self.name, self.ip)

    def interfaces_in_vlan(self, vlan):
        return Interface.objects.filter(switch=self, vlan=vlan)

    def shorten_interface_name(self, interface_name: str):
        interface_name = str(interface_name)
        if self.type == 'Cisco':
            if interface_name.find('TwentyFiveGigE') == 0:
                return interface_name.replace('TwentyFiveGigE', 'Twe')
            else:
                return re.sub(r'([A-Z][a-z])[a-zA-Z]*([0-9\/]+)', r'\1\2',
                              interface_name)
        elif self.type == 'Extreme':
            return re.sub(r'Slot:\s+([0-9]+), Port:\s+([0-9]+)', r'\1:\2',
                          interface_name)
        else:
            return interface_name

    def vlans(self):
        return self.vlan.filter(vlan__gt=1)

    def has_backup(self):
        if hasattr(settings, 'BACKUP_PATH'):
            backup_path = os.path.join(settings.BACKUP_PATH + '/' + self.name)
            return os.path.exists(backup_path)

    def has_tree(self):
        if apps.is_installed('switch_tree'):
            from switch_tree.models import Tree
            try:
                Tree.objects.get(switch=self)
                return True
            except Tree.DoesNotExist:
                return False

    def neighbor_interfaces(self):
        """
        Get interfaces with neighbors
        :return:
        """
        return self.interfaces.exclude(neighbor=None)

    def software(self):
        matches = None
        if self.type == 'Aruba' or self.type == 'ProCurve':
            matches = re.search(r'revision ([A-Z]+[0-9.]+)', self.description)
        elif self.type == 'Aruba CX':
            matches = re.search(r'([A-Z]{2}\.[\d.]+)', self.description)
        elif self.type == 'HP':
            matches = re.search(r'Release ([A-Z0-9]+)', self.description)
        elif self.type in ['Cisco', 'Cisco IOS', 'Cisco IOS XE']:
            matches = re.search(r'Version ([\w.()]+)', self.description)
        elif self.type == 'Extreme':
            matches = re.search(r'version ([\d.]+)', self.description)

        if matches:
            return matches.group(1)


class SwitchGroup(models.Model):
    grouping_key = models.CharField(max_length=50, unique=True)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def members(self):
        return Switch.objects.filter(name__istartswith=self.grouping_key)

    def switches(self):
        items = []
        for group in SwitchGroup.objects.filter(name=self.name):
            items += group.members()
        return items


class Vlan(models.Model):
    vlan = models.IntegerField(unique=True)
    on_switch = models.ManyToManyField(Switch, related_name='vlan')
    name = models.CharField(max_length=50, blank=True, null=True)
    has_ports = models.BooleanField(default=False)

    class Meta:
        ordering = ['vlan']

    #    unique_together = (('switch', 'vlan'),)

    def __str__(self):
        if self.name:
            return '%s (%d)' % (self.name, self.vlan)
        else:
            return str(self.vlan)


class Interface(models.Model):
    index = models.IntegerField()
    switch = models.ForeignKey(
        Switch,
        on_delete=models.CASCADE,
        related_name='interfaces'
    )
    interface = models.CharField(max_length=50)
    type = models.CharField('Interface type', max_length=50)
    vlan = models.ForeignKey(
        Vlan,
        on_delete=models.SET_NULL,
        blank=True, null=True,
        related_name='untagged_vlan')
    tagged_vlans = models.ManyToManyField(Vlan,
                                          related_name='tagged_vlans',
                                          blank=True)
    description = models.CharField(
        'User defined description for the interface',
        max_length=200, blank=True, null=True)
    status = models.IntegerField(null=True)
    admin_status = models.IntegerField(null=True)
    speed = models.BigIntegerField(blank=True, null=True)
    poe_status = models.CharField(max_length=50, blank=True, null=True)
    link_status_changed = models.DateField(null=True, blank=True)
    neighbor = models.ForeignKey(
        Switch, on_delete=models.SET_NULL,
        blank=True, null=True,
        related_name='neighbor')
    neighbor_string = models.CharField(
        max_length=500,
        blank=True, null=True)
    neighbor_set_by = models.ForeignKey(
        Switch,
        on_delete=models.SET_NULL,
        blank=True, null=True,
        related_name='neighbor_set_by')
    skip_mac = models.BooleanField(
        help_text='Do not load MAC-addresses for this interface',
        default=False)
    force_mac = models.BooleanField(
        help_text='Load MAC addresses even if the interface is trunk',
        default=False)
    aggregation = models.ForeignKey(
        'self',
        on_delete=models.SET_NULL,
        blank=True, null=True,
        related_name='aggregation_members',
        help_text='Aggregation virtual interface',
    )

    class Meta:
        unique_together = (('switch', 'index'),)
        ordering = ['index']

    def mac(self):
        macs = Mac.objects.filter(interface=self)
        return macs

    def ip(self):
        ip = []
        for mac in self.mac():
            arp = Arp.objects.filter(mac=mac.mac)
            if arp.count() == 0:
                ip.append(None)
                continue

            ip.append(arp[0].ip)
        return ip

    def status_format(self):
        status = {1: 'up',
                  2: 'down',
                  3: 'testing',
                  4: 'unknown',
                  5: 'dormant',
                  6: 'notPresent',
                  7: 'lowerLayerDown'}

        if self.status in status:
            return status[self.status]

    def speed_format(self):
        if not self.speed:
            return 'auto'
        # speed = int(int(self.speed)/1000000)
        speed = self.speed
        if speed < 1000:
            speed = '%dM' % speed
        else:
            speed = '%dG' % int(speed / 1000)
        return speed

    def css(self):
        # if self.link_status_changed # cellUnused

        if self.status == 1:
            # if not self.description:
            #    return 'cellWarning'
            # else:
            return 'cellActive'
        else:
            return 'cellDefault'

    def switch_string(self):
        return '%s on %s' % (self.interface, self.switch)

    def is_trunk(self):
        if self.tagged_vlans.count() > 0 or self.vlan is None:
            return True
        else:
            return False

    def __str__(self):
        return self.interface


class Mac(models.Model):
    interface = models.ForeignKey(
        Interface,
        on_delete=models.CASCADE,
        related_name='macs'
    )
    mac = models.CharField(max_length=12)
    last_seen = models.DateTimeField(auto_now=False, blank=True, null=True)

    def switch(self):
        return self.interface.switch

    def ip(self):
        return Arp.objects.get(mac=self.mac)

    def __str__(self):
        return self.mac

    def oui(self):
        prefix = self.mac[0:6]
        prefix = prefix.upper()

        prefix_info = Oui.objects.filter(prefix=prefix)
        if prefix_info.count() > 0:
            return prefix_info.first().vendor
        else:
            return ''


class Arp(models.Model):
    mac = models.CharField(max_length=12, unique=True, primary_key=True)
    ip = models.GenericIPAddressField()

    def __str__(self):
        return '%s %s' % (self.mac, self.ip)

    def vlan(self):
        mac_obj = Mac.objects.get(mac=self.mac)
        return mac_obj.interface.vlan

    def cnet(self):
        import re
        return re.sub(r'([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})\.[0-9]{1,3}', r'\1', self.ip)


class Oui(models.Model):
    prefix = models.CharField(max_length=6)
    vendor = models.CharField(max_length=100)

    def __str__(self):
        return self.prefix + ' ' + self.vendor

switchinfo/templates/switchinfo/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    {% if not title %}
        <title>Switchinfo</title>
    {% else %}
        <title>Switchinfo - {{ title|default:"" }}</title>
    {% endif %}

    <link href="{% static "switchinfo/switchinfo.css" %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'switchinfo/menu.css' %}" type="text/css">
    {% block head %}
    {% endblock %}
</head>

<body>
<div class="menu">
    <ul class="top_menu">
        <li><a href="{% url 'switchinfo:switches' %}">Switches</a></li>
        <li><a href="{% url 'switchinfo:vlans' %}">Vlans</a></li>
        <li><a href="{% url 'switchinfo:models' %}">Switch models</a></li>
        <li><a href="{% url 'switchinfo:groups' %}">Switch groups</a></li>
        <li><a href="{% url 'switchinfo:search' %}">Search</a></li>
    </ul>
</div>

<div id="content" class="flex">
    <h1>{{ title|capfirst }}</h1>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

switchinfo/templates/switchinfo/models.html
{% extends 'switchinfo/base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'switchinfo/switchinfo_fancy.css' %}" type="text/css">
{% endblock %}
{% block content %}
    <table class="switchinfo">
        <tr>
            <th>Series</th>
            <th>Count</th>
        </tr>
        {% for model in series %}
            <tr>
                <td>
                    <a href="{% url 'switchinfo:switches' %}?series={{ model.series|urlencode }}">{{ model.series }}</a>
                </td>
                <td>{{ model.count }}</td>
            </tr>
        {% endfor %}
    </table>
    <br/>
    <table class="switchinfo">
        <tr>
            <th>Model</th>
            <th>Count</th>
        </tr>
        {% for model in models %}
            <tr>
                <td>
                    <a href="{% url 'switchinfo:switches' %}?model={{ model.model|urlencode }}">{{ model.type }}&nbsp;{{ model.model }}</a>
                </td>
                <td>{{ model.count }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

switchinfo/templates/switchinfo/search.html
{% extends 'switchinfo/base.html' %}

{% block content %}
<form action="{% url 'switchinfo:search' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Search">
</form>

{% endblock %}

switchinfo/templates/switchinfo/switch.html
{% extends 'switchinfo/base.html' %}
{% load static %}
{% block head %}
    <script src="{% static 'switchinfo/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'switchinfo/collapse_vlans.js' %}"></script>
{% endblock %}

{% block content %}
    {% if switch.image %}
        <img src="{{ switch.image }}" />
    {% endif %}
    <table border="1">
        <tr>
            <th>Location</th>
            <td>{{ switch.location|default:"" }}</td>
        </tr>
        <tr>
            <th>Model</th>
            {% if switch.model %}
                <td>{{ switch.type|default:"" }}&nbsp;<a
                        href="{% url 'switchinfo:switches' %}?model={{ switch.model|urlencode }}">{{ switch.model }}</a>
                </td>
            {% else %}
            <td>{{ switch.type|default:"" }}&nbsp;{{ switch.model|default:"" }}</td>
            {% endif %}
        </tr>
        <tr>
            <th>Series</th>
            {% if switch.series %}
                <td><a href="{% url 'switchinfo:switches' %}?series={{ switch.series|urlencode }}">{{ switch.series }}</a></td>
            {% else %}
                <td>&nbsp;</td>
            {% endif %}
        </tr>
        <tr>
            <th>Description</th>
            <td>{{ switch.description|default:""|linebreaksbr }}</td>
        </tr>

    </table>
    <p>
    {% include 'switchinfo/switch_table.html' %}
    </p>
    <p>
        <a href="{% url 'switchinfo:switch_load_interfaces' switch_name=switch.name %}">Update interfaces</a>
        <br /><a href="{% url 'switchinfo:switch_load_mac' switch_name=switch.name %}">Update MAC</a>
    {% if switch.has_backup %}
        <br /><a href="{{ backup_web_base }}{{ switch.name }}">Show config backup</a>
    {% endif %}
        <br /><a href="{% url 'switchinfo:switch_vlans' switch_name=switch.name %}">Show vlans on switch</a>
    </p>
{% endblock %}

switchinfo/templates/switchinfo/switch_list.html
<table class="switchinfo">
    <tr>
        <th>Name</th>
        <th>IP</th>
        <th>Model</th>
        <th>Software</th>
    </tr>
    {% for switch in switches %}
        <tr>
            <td>
                {% if not ip_link %}
                    <a href="{% url 'switchinfo:switch' name=switch.name %}">{{ switch.name }}</a>
                {% else %}
                    <a href="{% url 'switchinfo:switch' ip=switch.ip %}">{{ switch.name }}</a>
                {% endif %}
            </td>
            <td>{{ switch.ip }}</td>
            <td>{{ switch.type|default:"" }}&nbsp;{{ switch.model }}</td>
            <td>{{ switch.software|default:"" }}</td>
        </tr>
    {% endfor %}
</table>

switchinfo/templates/switchinfo/switch_table.html
{% load static %}
{% if interfaces %}
	<table border="1">
	<tr class="tblHead">
		<th>Port</th>
		<th>VLAN</th>
		<th>Status</th>
		{% if switch.has_poe %}<th>PoE</th>{% endif %}
		<th>Speed</th>
		<th>Description</th>
		<th>CDP/LLDP</th>
		<th>MAC</th>
		<th>NIC Manufacturer</th>
		<th>IP address</th>
		<th>DNS name</th>
	</tr>
	{% for interface in interfaces %}
		<tr class="{{interface.css}}">
            <td title="{{ interface.index }}">{{ interface.interface }}</td>
            {% if not interface.is_trunk %}
                <td><a href="{% url 'switchinfo:vlan' vlan=interface.vlan.vlan %}">{{ interface.vlan }}</a></td>
            {% elif interface.tagged_vlans.exists %}
                <td title="Show tagged vlans">
                    <span class="show_tagged" data-id="{{ interface.id }}">trunk</span>
                    {% if interface.vlan %}
                        (<a href="{% url 'switchinfo:vlan' vlan=interface.vlan.vlan %}">{{ interface.vlan }}</a>)
                    {% endif %}

                    <br/>
                    <div id="tagged_{{ interface.id }}" class="tagged_vlans" style="display: none">
                        {% for vlan in interface.tagged_vlans.all %}
                            <a href="{% url 'switchinfo:vlan' vlan=vlan.vlan %}">{{ vlan }}</a><br/>
                        {% endfor %}
                    </div>
                </td>
            {% else %}
			<td>{{interface.vlan|default:"trunk"}}</td>
            {% endif %}
			<td>{{interface.status_format}} {% if interface.link_status_changed %}since {{ interface.link_status_changed }}{% endif %}</td>
			{% if switch.has_poe %}<td>{{interface.poe_status|default:""}}</td>{% endif %}
			<td>{{interface.speed_format}}</td>
			<td>{{interface.description|default:""}}</td>
			{% if interface.neighbor %}
			<td><a href="{% url 'switchinfo:switch' name=interface.neighbor.name %}">{{interface.neighbor.name}}</a><br />{{ interface.neighbor.ip }}</td>
			{% else %}
			<td class="port_neighbor">{{interface.neighbor_string|default:""|linebreaksbr}}</td>
			{% endif %}

            {% if interface.admin_status == 2 %}
                <td colspan="4" class="cellWarning">Admin disabled</td>
            {% elif interface.aggregation_id %}
                <td colspan="4" class="cellEtherChannel">Part of EtherChannel {{ interface.aggregation }}</td>
            {% elif not interface.is_trunk or interface.force_mac %}
			<td style="font-family: monospace;">
                {% for mac in interface.mac %}
                {{mac}}<br />
                {% endfor %}
			</td>
			<td style="font-family: monospace;">
                {% for mac in interface.mac %}
                {{mac.oui}}<br />
                {% endfor %}
			</td>
			<td style="font-family: monospace;">
                {% for ip in interface.ip %}
			    {{ip|default:""}}<br />
			    {% endfor %}
            </td>
            <td></td>
            {% else %}
                <td colspan="4"><em>trunk port</em></td>
            {% endif %}
		</tr>
    {% endfor %}
	</table>
{% endif %}

switchinfo/templates/switchinfo/switches.html
{% extends 'switchinfo/base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'switchinfo/switchinfo_fancy.css' %}" type="text/css">
{% endblock %}
{% block content %}
    {% include 'switchinfo/switch_list.html' %}
{% endblock %}

switchinfo/templates/switchinfo/switches_group.html
{% extends 'switchinfo/base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'switchinfo/switchinfo_fancy.css' %}" type="text/css">
{% endblock %}
{% block content %}
    {% for group, switches in groups %}
        <h2>{{ group|default:"No group" }}</h2>
        {% include 'switchinfo/switch_list.html' %}
    {% endfor %}
{% endblock %}

switchinfo/templates/switchinfo/vlan.html
{% extends 'switchinfo/base.html' %}
{% load static %}

{% block head %}
    <script src="{% static 'switchinfo/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'switchinfo/collapse_vlans.js' %}"></script>
{% endblock %}

{% block content %}
{% for switch, interfaces in switches %}
    {% if interfaces %}
	<h2><a href="{% url 'switchinfo:switch' name=switch.name %}">{{switch}}</a></h2>
	{% include 'switchinfo/switch_table.html' %}
    {% else %}
        Vlan exists on <a href="{% url 'switchinfo:switch' name=switch.name %}">{{ switch }}</a> without ports<br />
    {% endif %}
{% endfor %}
{% endblock %}

switchinfo/templates/switchinfo/vlan_list.html
<table class="switchinfo">
    <tr>
        <th>Number</th>
        <th>Name</th>
    </tr>

    {% for vlan in vlans %}
        <tr>
            <td><a href="{% url 'switchinfo:vlan' vlan=vlan.vlan %}">{{ vlan.vlan }}</a></td>
            <td>{{ vlan.name }}</td>
        </tr>
    {% endfor %}
</table>

switchinfo/templates/switchinfo/vlans.html
{% extends 'switchinfo/base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'switchinfo/switchinfo_fancy.css' %}" type="text/css">
{% endblock %}

{% block content %}
    {% include 'switchinfo/vlan_list.html' %}
{% endblock %}

switchinfo/templates/switchinfo/vlans_cli.html
{% for vlan in vlans %}
vlan {{ vlan.vlan }}
name "{{ vlan.name }}"
exit
{% endfor %}

switchinfo/templates/switchinfo/vlans_on_switch.html
{% extends 'switchinfo/base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'switchinfo/switchinfo_fancy.css' %}" type="text/css">
{% endblock %}
{% block content %}
    {% include 'switchinfo/vlan_list.html' %}
    {% if switch.has_tree %}
        <a href="{% url 'switch_tree:backtrace' name=switch_name %}">Show upstream switches and missing vlans</a><br/>
    {% endif %}
    <br/><a href="{% url 'switchinfo:switch_vlans_cli' switch_name=switch.name %}">Show vlan CLI</a>
{% endblock %}